apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-read
  namespace: app
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","secrets"]
    verbs: ["get","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-read-binding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: app-sa
roleRef:
  kind: Role
  name: app-read
  apiGroup: rbac.authorization.k8s.io
