apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  APP_MODE: "blank"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB_STORAGE: "0"
  REDIS_DB_STREAMS: "1"
  # Basic Redis setup - put your queue names here
  MOTION_DETECTION_QUEUE: "motion_queue"     # <- change this to whatever you want
  IMAGE_PROCESSOR_QUEUE: "image_queue"       # <- change this to whatever you want
  RESULTS_QUEUE: "results_queue"             # <- change this to whatever you want

  # Optimized worker settings for better performance
  MOTION_DETECTION_BATCH_SIZE: "8"           # <- optimized batch size for motion detection
  IMAGE_PROCESSOR_BATCH_SIZE: "15"           # <- optimized batch size for image processing
  WORKER_POLL_TIMEOUT: "500"                 # <- reduced timeout for better responsiveness (ms)

  # Performance optimization settings
  MAX_IMAGE_WIDTH: "640"                     # <- max width for general processing optimization
  MOTION_DETECTION_RESIZE_WIDTH: "640"       # <- width for motion detection (640px for good balance)
  FACE_ANALYSIS_JPEG_QUALITY: "90"           # <- high quality JPEG for face analysis (90 = high quality)
  ENABLE_PERFORMANCE_LOGGING: "true"         # <- enable detailed performance logging

  # Face search configuration (RedisSearch only)
  REDISEARCH_INDEX_NAME: "faces_idx"         # <- RedisSearch index name for face vectors

  # Redis connection configuration
  REDIS_MAX_RETRIES: "30"                    # <- maximum connection retry attempts (30 = ~5 minutes with backoff)
  REDIS_BASE_DELAY: "1.0"                    # <- initial retry delay in seconds
  REDIS_MAX_DELAY: "30.0"                    # <- maximum retry delay in seconds (exponential backoff cap)

  # Convex Database Integration
  CONVEX_BASE_URL: "https://quirky-capybara-814.convex.site"   # <- Convex API base URL
  CONVEX_USER_ID: "j977j0gpwnr0k8zj37brahvxxx7rpsmc"  # <- User ID for event association
  CONVEX_EVENT_NAME: "Face Detection Event"  # <- Default event name
  CONVEX_EVENT_PRICE: "0.0"                  # <- Default event price
