apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  APP_MODE: "blank"
  REDIS_HOST: "redis.app.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB_STORAGE: "0"
  REDIS_DB_STREAMS: "1"
  # Basic Redis setup - put your queue names here
  MOTION_DETECTION_QUEUE: "motion_queue"     # <- change this to whatever you want
  IMAGE_PROCESSOR_QUEUE: "image_queue"       # <- change this to whatever you want
  RESULTS_QUEUE: "results_queue"             # <- change this to whatever you want

  # Optimized worker settings for better performance
  MOTION_DETECTION_BATCH_SIZE: "8"           # <- optimized batch size for motion detection
  IMAGE_PROCESSOR_BATCH_SIZE: "15"           # <- optimized batch size for image processing
  WORKER_POLL_TIMEOUT: "500"                 # <- reduced timeout for better responsiveness (ms)

  # Performance optimization settings
  MAX_IMAGE_WIDTH: "640"                     # <- max width for general processing optimization
  MOTION_DETECTION_RESIZE_WIDTH: "640"       # <- width for motion detection (640px for good balance)
  FACE_ANALYSIS_JPEG_QUALITY: "90"           # <- high quality JPEG for face analysis (90 = high quality)
  ENABLE_PERFORMANCE_LOGGING: "true"         # <- enable detailed performance logging
