apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: app
  labels: { app: worker }
spec:
  replicas: 2
  selector: { matchLabels: { app: worker } }
  template:
    metadata:
      labels: { app: worker }
    spec:
      serviceAccountName: app-sa
      containers:
        - name: worker
          image: your-app:dev               # same image; role differs via env
          imagePullPolicy: IfNotPresent
          env:
            - name: ROLE
              value: "worker"
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef:    { name: app-secrets }
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
