# Redis service (required for worker connectivity)
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
---
# Controller service (optional - only needed if exposing ports)
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: app
spec:
  selector: { app: controller }
  ports:
    - name: http
      port: 80
      targetPort: 8000   # match your container port if/when you add one
  type: ClusterIP
