# Legacy HPA - DEPRECATED
# Use 52-hpa-motion-detection-workers.yaml and 53-hpa-image-processor-workers.yaml instead
# This file is kept for backward compatibility but should be removed after migration

# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: worker-hpa
#   namespace: app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: worker
#   minReplicas: 2
#   maxReplicas: 20
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 70
