# HPA for Motion Detection Workers
# (needs metrics-server installed)

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: motion-detection-worker-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: motion-detection-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
