name: Ruff

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install --upgrade ruff

      # Fail if files aren’t formatted the Ruff way
      - run: ruff format --check .

      # Fail on lint violations
      - run: ruff check .
